// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: delete.sql

package sqlite

import (
	"context"
)

const deleteAllResultsOlderThanXDays = `-- name: DeleteAllResultsOlderThanXDays :exec
DELETE FROM results
WHERE created_at < datetime('now', '-1 day' * ?)
`

func (q *Queries) DeleteAllResultsOlderThanXDays(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteAllResultsOlderThanXDays, dollar_1)
	return err
}

const deleteAllResultsOlderThanXHours = `-- name: DeleteAllResultsOlderThanXHours :exec
DELETE FROM results
WHERE created_at < datetime('now', '-1 hour' * ?)
`

func (q *Queries) DeleteAllResultsOlderThanXHours(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteAllResultsOlderThanXHours, dollar_1)
	return err
}

const deleteAllResultsWithQuery = `-- name: DeleteAllResultsWithQuery :exec
DELETE FROM results
WHERE query = ?
`

func (q *Queries) DeleteAllResultsWithQuery(ctx context.Context, query string) error {
	_, err := q.db.ExecContext(ctx, deleteAllResultsWithQuery, query)
	return err
}
