// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"time"
)

type EngineRank struct {
	ID               int64
	EngineName       string
	EngineRank       int64
	EnginePage       int64
	EngineOnPageRank int64
	ResultID         int64
}

type ImageResult struct {
	ID                   int64
	ImageOriginalHeight  int64
	ImageOriginalWidth   int64
	ImageThumbnailHeight int64
	ImageThumbnailWidth  int64
	ImageThumbnailUrl    string
	ImageSource          string
	ImageSourceUrl       string
	ResultID             int64
}

type Result struct {
	ID          int64
	Query       string
	Url         string
	Rank        int64
	Score       float64
	Title       string
	Description string
	CreatedAt   time.Time
}
