// Code generated by "stringer -type=Name"; DO NOT EDIT.

package engines

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Bing-1]
	_ = x[Brave-2]
	_ = x[DuckDuckGo-3]
	_ = x[Etools-4]
	_ = x[Google-5]
	_ = x[Mojeek-6]
	_ = x[Presearch-7]
	_ = x[Qwant-8]
	_ = x[Startpage-9]
	_ = x[Swisscows-10]
	_ = x[Yahoo-11]
	_ = x[Yandex-12]
	_ = x[Yep-13]
}

const _Name_name = "UndefinedBingBraveDuckDuckGoEtoolsGoogleMojeekPresearchQwantStartpageSwisscowsYahooYandexYep"

var _Name_index = [...]uint8{0, 9, 13, 18, 28, 34, 40, 46, 55, 60, 69, 78, 83, 89, 92}

func (i Name) String() string {
	if i < 0 || i >= Name(len(_Name_index)-1) {
		return "Name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Name_name[_Name_index[i]:_Name_index[i+1]]
}
