// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: delete.sql

package postgres

import (
	"context"
)

const deleteAllResultsOlderThanXDays = `-- name: DeleteAllResultsOlderThanXDays :exec
DELETE FROM results
WHERE created_at < NOW() - INTERVAL '1 day' * $1
`

func (q *Queries) DeleteAllResultsOlderThanXDays(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, deleteAllResultsOlderThanXDays, dollar_1)
	return err
}

const deleteAllResultsOlderThanXHours = `-- name: DeleteAllResultsOlderThanXHours :exec
DELETE FROM results
WHERE created_at < NOW() - INTERVAL '1 hour' * $1
`

func (q *Queries) DeleteAllResultsOlderThanXHours(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, deleteAllResultsOlderThanXHours, dollar_1)
	return err
}

const deleteAllResultsWithQuery = `-- name: DeleteAllResultsWithQuery :exec
DELETE FROM results
WHERE query = $1
`

func (q *Queries) DeleteAllResultsWithQuery(ctx context.Context, query string) error {
	_, err := q.db.Exec(ctx, deleteAllResultsWithQuery, query)
	return err
}
