// Code generated by "enginer -type=Name -packagename search -output ../engine_enginer.go"; DO NOT EDIT.

package search

import "github.com/hearchco/agent/src/search/scraper"
import "github.com/hearchco/agent/src/search/engines"
import "github.com/hearchco/agent/src/search/engines/bing"
import "github.com/hearchco/agent/src/search/engines/bingimages"
import "github.com/hearchco/agent/src/search/engines/brave"
import "github.com/hearchco/agent/src/search/engines/duckduckgo"
import "github.com/hearchco/agent/src/search/engines/etools"
import "github.com/hearchco/agent/src/search/engines/google"
import "github.com/hearchco/agent/src/search/engines/googleimages"
import "github.com/hearchco/agent/src/search/engines/googlescholar"
import "github.com/hearchco/agent/src/search/engines/mojeek"
import "github.com/hearchco/agent/src/search/engines/presearch"
import "github.com/hearchco/agent/src/search/engines/qwant"
import "github.com/hearchco/agent/src/search/engines/startpage"
import "github.com/hearchco/agent/src/search/engines/swisscows"
import "github.com/hearchco/agent/src/search/engines/yahoo"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the enginer command to generate them again.
	var x [1]struct{}
	_ = x[engines.UNDEFINED-(0)]
	_ = x[engines.BING-(1)]
	_ = x[engines.BINGIMAGES-(2)]
	_ = x[engines.BRAVE-(3)]
	_ = x[engines.DUCKDUCKGO-(4)]
	_ = x[engines.ETOOLS-(5)]
	_ = x[engines.GOOGLE-(6)]
	_ = x[engines.GOOGLEIMAGES-(7)]
	_ = x[engines.GOOGLESCHOLAR-(8)]
	_ = x[engines.MOJEEK-(9)]
	_ = x[engines.PRESEARCH-(10)]
	_ = x[engines.QWANT-(11)]
	_ = x[engines.STARTPAGE-(12)]
	_ = x[engines.SWISSCOWS-(13)]
	_ = x[engines.YAHOO-(14)]
	_ = x[engines.YEP-(15)]
}

const enginerLen = 16

func enginerArray() [enginerLen]scraper.Enginer {
	var engineArray [enginerLen]scraper.Enginer
	engineArray[engines.BING] = bing.New()
	engineArray[engines.BINGIMAGES] = bingimages.New()
	engineArray[engines.BRAVE] = brave.New()
	engineArray[engines.DUCKDUCKGO] = duckduckgo.New()
	engineArray[engines.ETOOLS] = etools.New()
	engineArray[engines.GOOGLE] = google.New()
	engineArray[engines.GOOGLEIMAGES] = googleimages.New()
	engineArray[engines.GOOGLESCHOLAR] = googlescholar.New()
	engineArray[engines.MOJEEK] = mojeek.New()
	engineArray[engines.PRESEARCH] = presearch.New()
	engineArray[engines.QWANT] = qwant.New()
	engineArray[engines.STARTPAGE] = startpage.New()
	engineArray[engines.SWISSCOWS] = swisscows.New()
	engineArray[engines.YAHOO] = yahoo.New()
	return engineArray
}

func searcherArray() [enginerLen]scraper.Searcher {
	var engineArray [enginerLen]scraper.Searcher
	engineArray[engines.BING] = bing.New()
	engineArray[engines.BINGIMAGES] = bingimages.New()
	engineArray[engines.BRAVE] = brave.New()
	engineArray[engines.DUCKDUCKGO] = duckduckgo.New()
	engineArray[engines.ETOOLS] = etools.New()
	engineArray[engines.GOOGLE] = google.New()
	engineArray[engines.GOOGLEIMAGES] = googleimages.New()
	engineArray[engines.GOOGLESCHOLAR] = googlescholar.New()
	engineArray[engines.MOJEEK] = mojeek.New()
	engineArray[engines.PRESEARCH] = presearch.New()
	engineArray[engines.QWANT] = qwant.New()
	engineArray[engines.STARTPAGE] = startpage.New()
	engineArray[engines.SWISSCOWS] = swisscows.New()
	engineArray[engines.YAHOO] = yahoo.New()
	return engineArray
}

func suggesterArray() [enginerLen]scraper.Suggester {
	var engineArray [enginerLen]scraper.Suggester
	engineArray[engines.DUCKDUCKGO] = duckduckgo.New()
	engineArray[engines.GOOGLE] = google.New()
	return engineArray
}
